export const SET_DRAFT_POST_PARAMS = 'SET_DRAFT_POST_PARAMS';

export const DELETE_POST = 'DELETE_POST';
export const CREATE_POST = 'CREATE_POST';
export const SET_POSTS = 'SET_POSTS';

export const NAVIGATE_HOME = 'NAVIGATE_HOME';
export const NAVIGATE_BACK = 'NAVIGATE_BACK';
